name: facestream-studio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - opencv
  - numpy
  - pillow
  - pip:
      - streamlit
      - mediapipe
      - ultralytics
      - face_recognition
